# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-06-27 21:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_and_registration_app', '0002_user_has_usable_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='DBusername',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
